'use client'
import { useEffect, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import user from '../page/api/users/index'
import Auth from '../app/Auth/page.jsx'
import util from '../page/api/users/index'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [user, setUser] = useState(null)

  useEffect(()=> {
    async function fetch(){
        const user = await util.getUser()
        setUser(user)
    }fetch()
  },[])

  return (
    <html lang="en">
      <body className={inter.className}>
        {user ? children : <Auth></Auth>}
        </body>
    </html>
  )
}
